# one char commands
alias cc='claude'
alias s='source'
alias d='orbctl'
alias g='git'
alias v='nvim'
alias k='kubectl'
alias y='yarn'
alias p='python'
alias m='make'
alias o='open .'


# alias docker='orbctl'
alias ll='ls -l'
alias la='ls -a'
alias dir='ls -ba'
alias vim='LANG=en_US.UTF-8 v'
alias vi='vim -u ~/.vim.d/general.vimrc ~/.vim.d/keys.vimrc'
alias git='LANG=en_US.UTF-8 git'
alias gut='git'
alias gs='git status --short'
alias gc='git commit'
alias gz='git cz'
alias gd='git diff'
alias gco='git checkout'
alias ga='git add'
alias gpl='git pull --rebase'
alias gplo='git pull --rebase origin'
alias gp='git push origin @'
alias gpp='git push origin production'
alias ts='tig status'
alias vgs='nvim $(git status --porcelain | cut -c 4-)'
alias gfs='git flow feature start'
alias gff='git flow feature finish'
alias gf='git flow'

alias cat='bat'
alias yanr='yarn'

alias :q='exit'
alias :x='exit'
