alias ll='ls -l'
alias la='ls -a'
alias dir='ls -ba'
alias vim='LANG=en_US.UTF-8 /usr/local/bin/vim'
alias v='vim'
alias k='kubectl'

alias vi='vim -u ~/.vim.d/general.vimrc ~/.vim.d/keys.vimrc'
alias git='LANG=en_US.UTF-8 git'
alias g='git'
alias gut='git'
alias gs='git status'
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout'
alias ga='git add'
alias gpl='git pull --rebase'
alias gplo='git pull --rebase origin'
alias gp='git push origin master'
alias gpp='git push origin production'
alias ts='tig status'
alias vgs='vim -p $(git status --porcelain | cut -c 4-)'
alias gfs='git flow feature start'
alias gff='git flow feature finish'
alias gf='git flow'
alias yanr='yarn'
alias :q='exit'
alias :x='exit'
